# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean Parent
email: sean.parent@stlab.cc
description: Too many projects, too little time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sean-parent.stlab.cc" # the base hostname & protocol for your site
twitter_username: SeanParent
github_username:  sean-parent

# Build settings
markdown: kramdown
highlighter: rouge

exclude: ["project.bbprojectd"]
exclude-tags: [ better-code ]

#wire this up
comments :
  provider : disqus
  disqus :
    short_name : seanparent
